[platformio]
build_dir = C:/Users/alison.tristao/.platformio/build_t_dongle

[env:tdongle-s3]
; esp32 --version
platform            = espressif32
board               = esp32-s3-devkitc-1
board_build.f_cpu   = 240000000L

; serial com
framework           = arduino
; max upload using USB into esp32-s3
upload_speed        = 3000000
monitor_speed       = 3000000
upload_port         = COM5
monitor_port        = COM5

; compiler flag
build_unflags = 
    -std=gnu++11
    
build_flags =
    -std=gnu++17
    -I include
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_RUNNING_CORE=1
    -DHIGH_FREQUENCY_INCOMMING_ESPNOW=1
    -DBAUDRATE=3000000

lib_deps =
    adafruit/Adafruit GFX Library @ ^1.11.10
    adafruit/Adafruit ST7735 and ST7789 Library @ ^1.11.0
    siara-cc/Sqlite3Esp32 @ 2.5
    https://github.com/AlisonTristao/TinyShell.git#571dee4af4b46318b1f4dcec93aa20b527cc25ae

board_build.flash_size = 16MB